[project]
name = "trm-text-coreml"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.7",
    "mlx>=0.29.2",
    "mlx-data>=0.2.0",
    "tqdm>=4.67.1",
    "torch",
    "torchvision",
    "torchaudio",
    "transformers",
]


